#!/usr/bin/env python3
"""Walk-forward stage2 runner for Alpha158 practice.

This script operates in three layers:

1. Trading-calendar driven walk-forward fold generation.
     - Folds can be generated by stepping backward yearly or forward weekly.
     - For each fold anchor t the split is strictly causal (no leakage):
         train = [t - (train_years + valid_years),  t - valid_years)  ← 7 y
         dev   = [t - valid_years,                  t)                ← 2 y
         test  = [t,                                t + test_years)    ← 3 y
     - The model is trained only on train/dev data and frozen before test.
     - A weekly mode (step_years=0, step_weeks>0) is also supported.

2. Segmented execution with fold-skip / resume support.
     - Folds are grouped by year chunks so the pipeline can be paused and
       resumed without re-running completed folds.
     - A fold is skipped if its output scores.csv already exists.

3. Full-cycle backtest aggregation.
     - All fold-level test-period predictions (all_scores.csv) are
       concatenated into a continuous signal series.
    - A live-aligned TopK walk-forward backtest generates a consolidated report:
       net-value curve, turnover, IC/ICIR, Sharpe, max drawdown, and
       a human-readable report_of_backtest.txt.

The latest fold outputs are copied to the root output dir so the existing
stage3/4/5/6 pipeline remains unchanged.

The implementation also clips the requested walk-forward end date to the
latest date available in the local qlib calendar and reports signal-coverage
diagnostics, which is important when annual folds only contribute short OOS
test windows.
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import shutil
import subprocess
import sys
import time
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlparse

import numpy as np
import pandas as pd
import yaml


ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts" / "practice"
WARM_START_STRATEGY = "previous_fold_checkpoint_v1"
MODEL_SPECS = [
    {
        "name": "xgboost",
        "template": ROOT / "examples" / "benchmarks" / "XGBoost" / "workflow_config_xgboost_Alpha158.yaml",
        "model_mode": "default",
    },
    {
        "name": "lightgbm",
        "template": ROOT / "examples" / "benchmarks" / "LightGBM" / "workflow_config_lightgbm_Alpha158.yaml",
        "model_mode": "robust",
    },
]


def _target_route_model_names() -> list[str]:
    return [str(spec["name"]) for spec in MODEL_SPECS if str(spec.get("universe_role", "")).strip().lower() == "target"]


def _model_spec_by_name(name: str) -> dict[str, object] | None:
    for spec in MODEL_SPECS:
        if str(spec.get("name")) == str(name):
            return spec
    return None


def _run(cmd: list[str], cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    subprocess.run(cmd, cwd=str(cwd or ROOT), env=env, check=True)


def _ts(date_str: str) -> pd.Timestamp:
    return pd.Timestamp(date_str)


def _fmt(ts: pd.Timestamp) -> str:
    return ts.strftime("%Y-%m-%d")


def _load_template(template_path: Path) -> dict:
    with open(template_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _load_pickle(path: Path):
    with open(path, "rb") as f:
        return pickle.load(f)


def _to_score_frame(obj, score_col: str = "score") -> pd.DataFrame:
    if isinstance(obj, pd.Series):
        df = obj.to_frame(score_col)
    elif isinstance(obj, pd.DataFrame):
        df = obj.copy()
        if score_col not in df.columns:
            first = df.columns[0]
            df = df[[first]].rename(columns={first: score_col})
        else:
            df = df[[score_col]]
    else:
        raise TypeError(f"Unsupported score object type: {type(obj)!r}")

    if isinstance(df.index, pd.MultiIndex):
        names = list(df.index.names)
        if len(names) >= 2:
            names[0] = "datetime"
            names[1] = "instrument"
            df.index = df.index.set_names(names)
    return df.sort_index()


def _to_label_frame(obj) -> pd.DataFrame:
    if isinstance(obj, pd.Series):
        df = obj.to_frame("label")
    elif isinstance(obj, pd.DataFrame):
        df = obj.copy()
        if "label" not in df.columns:
            first = df.columns[0]
            df = df[[first]].rename(columns={first: "label"})
        else:
            df = df[["label"]]
    else:
        raise TypeError(f"Unsupported label object type: {type(obj)!r}")

    if isinstance(df.index, pd.MultiIndex):
        names = list(df.index.names)
        if len(names) >= 2:
            names[0] = "datetime"
            names[1] = "instrument"
            df.index = df.index.set_names(names)
    return df.sort_index()


def _daily_rank_gaussian(score_df: pd.DataFrame, score_col: str) -> pd.DataFrame:
    out = score_df.copy()

    def _scale(group: pd.DataFrame) -> pd.DataFrame:
        s = pd.to_numeric(group[score_col], errors="coerce")
        if s.notna().sum() <= 1:
            group[score_col] = 0.0
            return group
        pct = s.rank(pct=True, method="average").clip(1e-6, 1 - 1e-6)
        group[score_col] = (pct - 0.5) * 2.0
        return group

    return out.groupby(level="datetime", group_keys=False).apply(_scale)


def _compute_daily_ic(pred_df: pd.DataFrame, label_df: pd.DataFrame) -> tuple[pd.Series, float, float]:
    joined = pred_df.join(label_df, how="inner").dropna()
    if joined.empty:
        return pd.Series(dtype=float), float("nan"), float("nan")

    ic_series = joined.groupby(level="datetime", group_keys=False).apply(
        lambda x: x["label"].corr(x["score"])
    ).dropna()
    ic_mean = float(ic_series.mean()) if not ic_series.empty else float("nan")
    ic_std = float(ic_series.std(ddof=1)) if len(ic_series) > 1 else float("nan")
    icir = ic_mean / ic_std if pd.notna(ic_std) and ic_std not in (0, 0.0) else float("nan")
    return ic_series, ic_mean, icir


def _compute_strategy_metrics(pred_df: pd.DataFrame, label_df: pd.DataFrame, hold_num: int) -> dict[str, float]:
    joined = pred_df.join(label_df, how="inner").dropna()
    if joined.empty:
        return {
            "annualized_return": float("nan"),
            "max_drawdown": float("nan"),
            "sharpe_ratio": float("nan"),
            "monthly_win_rate": float("nan"),
            "IC_mean": float("nan"),
            "ICIR": float("nan"),
            "win_rate": float("nan"),
        }

    daily_ic, ic_mean, icir = _compute_daily_ic(pred_df, label_df)
    topk = (
        joined.reset_index()
        .sort_values(["datetime", "score"], ascending=[True, False])
        .groupby("datetime", group_keys=False)
        .head(max(hold_num, 1))
    )
    daily_ret = topk.groupby("datetime")["label"].mean().sort_index()
    daily_ret.index = pd.to_datetime(daily_ret.index)

    if daily_ret.empty:
        ann_ret = mdd = sharpe = monthly_win = win_rate = float("nan")
    else:
        ann_ret = float((1 + daily_ret).prod() ** (252 / max(len(daily_ret), 1)) - 1)
        equity = (1 + daily_ret).cumprod()
        mdd = float((equity / equity.cummax() - 1).min())
        std = float(daily_ret.std(ddof=1)) if len(daily_ret) > 1 else float("nan")
        sharpe = float(daily_ret.mean() / std * np.sqrt(252)) if pd.notna(std) and std > 0 else float("nan")
        monthly = (1 + daily_ret).resample("ME").prod() - 1
        monthly_win = float((monthly > 0).mean()) if not monthly.empty else float("nan")
        win_rate = float((daily_ret > 0).mean()) if not daily_ret.empty else float("nan")

    return {
        "annualized_return": ann_ret,
        "max_drawdown": mdd,
        "sharpe_ratio": sharpe,
        "monthly_win_rate": monthly_win,
        "IC_mean": ic_mean,
        "ICIR": icir,
        "win_rate": win_rate,
        "ic_days": float(len(daily_ic)),
    }


def _compute_ensemble_weights(validation_ics: dict[str, float]) -> dict[str, float]:
    ordered_names = [str(spec["name"]) for spec in MODEL_SPECS]
    route_map = {name: str((_model_spec_by_name(name) or {}).get("route", "default")) for name in ordered_names}
    raw_map = {}
    for name in ordered_names:
        val = float(validation_ics.get(name, np.nan))
        raw_map[name] = max(val, 0.0) if np.isfinite(val) else 0.0

    unique_routes = list(dict.fromkeys(route_map.values()))
    if len(unique_routes) <= 1:
        raw = np.array([raw_map[name] for name in ordered_names], dtype=float)
        total = float(raw.sum())
        if total <= 1e-12:
            weights = np.repeat(1.0 / max(len(ordered_names), 1), len(ordered_names))
        else:
            weights = raw / total
        return {name: float(weight) for name, weight in zip(ordered_names, weights)}

    route_strength = {}
    for route in unique_routes:
        route_names = [name for name in ordered_names if route_map[name] == route]
        route_raw = np.array([raw_map[name] for name in route_names], dtype=float)
        route_strength[route] = float(route_raw.mean()) if route_raw.size else 0.0

    route_total = float(sum(route_strength.values()))
    if route_total <= 1e-12:
        route_weights = {route: 1.0 / max(len(unique_routes), 1) for route in unique_routes}
    else:
        route_weights = {route: strength / route_total for route, strength in route_strength.items()}

    weights: dict[str, float] = {}
    for route in unique_routes:
        route_names = [name for name in ordered_names if route_map[name] == route]
        route_raw = np.array([raw_map[name] for name in route_names], dtype=float)
        within_total = float(route_raw.sum())
        if within_total <= 1e-12:
            within_weights = np.repeat(1.0 / max(len(route_names), 1), len(route_names))
        else:
            within_weights = route_raw / within_total
        for name, within_weight in zip(route_names, within_weights):
            weights[name] = float(route_weights[route] * within_weight)

    final_total = float(sum(weights.values()))
    if final_total > 0:
        weights = {name: float(weight / final_total) for name, weight in weights.items()}
    return weights


def _combine_model_predictions(model_frames: dict[str, pd.DataFrame], weights: dict[str, float]) -> pd.DataFrame:
    combined = None
    target_index = None
    target_names = set(_target_route_model_names())
    for name, frame in model_frames.items():
        score_df = _to_score_frame(frame, score_col="score")
        if name in target_names:
            target_index = score_df.index if target_index is None else target_index.intersection(score_df.index)
        score_df = _daily_rank_gaussian(score_df, "score").rename(columns={"score": f"score_{name}"})
        if combined is None:
            combined = score_df
        else:
            combined = combined.join(score_df, how="outer")

    if combined is None or combined.empty:
        raise RuntimeError("No model predictions available for ensemble")

    if target_index is not None and len(target_index) > 0:
        combined = combined.reindex(target_index)

    score_cols = []
    combined = combined.sort_index()
    for name in weights:
        col = f"score_{name}"
        if col in combined.columns:
            combined[col] = pd.to_numeric(combined[col], errors="coerce").fillna(0.0)
            score_cols.append(col)

    combined["score"] = 0.0
    for name, weight in weights.items():
        col = f"score_{name}"
        if col in combined.columns:
            combined["score"] = combined["score"] + combined[col] * float(weight)

    keep_cols = [*score_cols, "score"]
    return combined[keep_cols]


def _build_synthetic_run_dir(
    ensemble_run_dir: Path,
    pred_df: pd.DataFrame,
    label_df: pd.DataFrame,
    validation_ics: dict[str, float],
    weights: dict[str, float],
) -> None:
    artifacts = ensemble_run_dir / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)
    with open(artifacts / "pred.pkl", "wb") as f:
        pickle.dump(pred_df[["score"]], f)
    with open(artifacts / "label.pkl", "wb") as f:
        pickle.dump(label_df[["label"]], f)
    (artifacts / "ensemble_metadata.json").write_text(
        json.dumps({"validation_ic": validation_ics, "weights": weights}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _augment_exported_scores(
    fold_output: Path,
    pred_date: str,
    weights: dict[str, float],
    validation_ics: dict[str, float],
    strategy_metrics: dict[str, float],
) -> dict[str, object]:
    scores_csv = fold_output / "scores.csv"
    metrics_csv = fold_output / "metrics.csv"
    all_scores_csv = fold_output / "all_scores.csv"
    if not scores_csv.exists() or not metrics_csv.exists():
        raise FileNotFoundError(f"Fold export missing required files under {fold_output}")

    scores_df = pd.read_csv(scores_csv)
    metrics_df = pd.read_csv(metrics_csv)

    scores_df["score_final"] = pd.to_numeric(scores_df.get("score"), errors="coerce")
    scores_df["pred_date"] = pred_date
    scores_df["date"] = pred_date
    for name, weight in weights.items():
        scores_df[f"weight_{name}"] = float(weight)
        scores_df[f"valid_ic_{name}"] = float(validation_ics.get(name, np.nan))
    for key, value in strategy_metrics.items():
        scores_df[key] = value

    metrics_payload = metrics_df.iloc[0].to_dict() if not metrics_df.empty else {}
    metrics_payload.update(strategy_metrics)
    metrics_payload.update({f"weight_{name}": float(weight) for name, weight in weights.items()})
    metrics_payload.update({f"valid_ic_{name}": float(validation_ics.get(name, np.nan)) for name in weights})
    metrics_payload["pred_date"] = pred_date
    metrics_payload["ensemble_models"] = ",".join(weights.keys())

    scores_df.to_csv(scores_csv, index=False, encoding="utf-8-sig")
    pd.DataFrame([metrics_payload]).to_csv(metrics_csv, index=False, encoding="utf-8-sig")

    if all_scores_csv.exists():
        all_scores_df = pd.read_csv(all_scores_csv)
        if "score_final" not in all_scores_df.columns and "score" in all_scores_df.columns:
            all_scores_df["score_final"] = pd.to_numeric(all_scores_df["score"], errors="coerce")
            all_scores_df.to_csv(all_scores_csv, index=False, encoding="utf-8-sig")

    fold_metrics = dict(metrics_payload)
    fold_metrics["score_final_mean"] = float(pd.to_numeric(scores_df["score_final"], errors="coerce").mean())
    return fold_metrics


def _init_qlib_from_template(template_path: Path, uri_folder: str) -> dict:
    """Initialize qlib once so we can query the trading calendar."""
    import qlib
    from qlib.config import C

    cfg = _load_template(template_path)
    qlib_init = cfg.get("qlib_init", {})
    exp_manager = C["exp_manager"]
    exp_manager["kwargs"]["uri"] = "file:" + str(Path(os.getcwd()).resolve() / uri_folder)
    qlib.init(**qlib_init, exp_manager=exp_manager)
    return cfg


def _load_trade_calendar(template_path: Path, uri_folder: str, start_date: str, end_date: str) -> tuple[dict, pd.DatetimeIndex]:
    cfg = _init_qlib_from_template(template_path, uri_folder)
    from qlib.data import D

    calendar = pd.DatetimeIndex(pd.to_datetime(D.calendar(start_time=start_date, end_time=end_date, freq="day")))
    calendar = calendar.sort_values().unique()
    if len(calendar) == 0:
        raise RuntimeError("No trading calendar dates loaded")
    return cfg, pd.DatetimeIndex(calendar)


def _align_left(calendar: pd.DatetimeIndex, target: pd.Timestamp) -> tuple[int, pd.Timestamp]:
    pos = int(calendar.searchsorted(pd.Timestamp(target), side="left"))
    if pos >= len(calendar):
        raise IndexError(f"target {target} is after the available calendar range")
    return pos, pd.Timestamp(calendar[pos])


def _align_right(calendar: pd.DatetimeIndex, target: pd.Timestamp) -> tuple[int, pd.Timestamp]:
    pos = int(calendar.searchsorted(pd.Timestamp(target), side="right")) - 1
    if pos < 0:
        raise IndexError(f"target {target} is before the available calendar range")
    return pos, pd.Timestamp(calendar[pos])


def _weekly_last_trade_dates(calendar: pd.DatetimeIndex) -> pd.DatetimeIndex:
    """Last trading day of each ISO week."""
    s = pd.Series(calendar, index=calendar)
    weekly = s.groupby([calendar.isocalendar().year, calendar.isocalendar().week]).max()
    return pd.DatetimeIndex(pd.to_datetime(weekly.values)).sort_values().unique()


def _yearly_first_trade_dates(calendar: pd.DatetimeIndex) -> pd.DatetimeIndex:
    """First trading day of each calendar year."""
    s = pd.Series(calendar, index=calendar)
    yearly = s.groupby(calendar.year).min()
    return pd.DatetimeIndex(pd.to_datetime(yearly.values)).sort_values().unique()


def _build_fold_dates(
    calendar: pd.DatetimeIndex,
    start_date: str,
    end_date: str,
    step_weeks: int = 1,
    step_years: int = 0,
    test_years: int = 3,
    test_weeks: int = 52,
    train_years: int = 7,
    valid_years: int = 2,
    train_base_start: str = "2008-01-01",
    history_years: int | None = None,
) -> list[dict[str, str]]:
    """Build walk-forward folds aligned to the trading calendar.

    Two modes (mutually exclusive; step_years takes priority when > 0):

      Annual mode (step_years > 0):
        Anchors are generated by stepping backward from end_date one year at a
                                time, stopping when the required train window would fall before
                                train_base_start.  The test horizon is measured in years and the
                                stored OOS evaluation horizon is extended until the next yearly
                                retrain date so the aggregated backtest is contiguous.

      Weekly mode (step_years = 0, step_weeks > 0):
        Anchors are the last trading day of every ISO week within
        [start_date, end_date].  Iteration is forward.  test_end is the
        last trading day of the following step_weeks week(s).

    For any anchor t the non-overlapping windows are:
            train = [t - (train_years + valid_years),  t - valid_years)  ← train_years long
            dev   = [t - valid_years,                  t)                ← valid_years long
            test  = [t,                                t + test_years)
    """
    use_annual = step_years > 0
    if not use_annual and step_weeks <= 0:
        raise ValueError("Either step_years or step_weeks must be positive")
    if test_years <= 0 or test_weeks <= 0:
        raise ValueError("test_years and test_weeks must be positive")

    _, end_ts = _align_right(calendar, pd.Timestamp(end_date))
    base_start_ts = pd.Timestamp(train_base_start)
    items: list[dict[str, str]] = []

    if use_annual:
        # ── Annual mode: walk BACKWARD from T ──────────────────────────────
        # t_end steps backward: T, T-1y, T-2y, …
        # For each t_end:
        #   test  = [t_end - test_years,  t_end]     ← last test_years of data up to t_end
        #   signal_date = test_start = t_end - test_years  (aligned to calendar)
        #   dev   = [signal_date - valid_years,  signal_date)
        #   train = [signal_date - (train_years+valid_years),  dev_start)
        # Stop when train_start_target < train_base_start.
        t_end = end_ts
        min_signal_date = end_ts - pd.DateOffset(years=history_years) if history_years and history_years > 0 else None
        while True:
            # Derive test_start from t_end
            test_start_target = t_end - pd.DateOffset(years=test_years)
            test_start_idx = int(calendar.searchsorted(test_start_target, side="left"))
            if test_start_idx >= len(calendar):
                t_end -= pd.DateOffset(years=step_years)
                continue
            signal_date = pd.Timestamp(calendar[test_start_idx])
            test_end = t_end  # guaranteed to be in calendar (aligned above)

            if min_signal_date is not None and signal_date < min_signal_date:
                break

            # Guard: enough history for a full train window
            train_start_target = signal_date - pd.DateOffset(years=train_years + valid_years)
            if train_start_target < base_start_ts:
                break

            # dev: [signal_date - valid_years, last trading day strictly before signal_date]
            valid_end_idx, valid_end = _align_right(calendar, signal_date - pd.Timedelta(days=1))
            valid_start_target = signal_date - pd.DateOffset(years=valid_years)
            valid_start_idx = int(calendar.searchsorted(valid_start_target, side="left"))
            if valid_start_idx > valid_end_idx:
                t_end -= pd.DateOffset(years=step_years)
                continue
            valid_start = pd.Timestamp(calendar[valid_start_idx])

            # train: ends just before dev_start
            train_end_idx = valid_start_idx - 1
            if train_end_idx < 0:
                t_end -= pd.DateOffset(years=step_years)
                continue
            train_end = pd.Timestamp(calendar[train_end_idx])
            train_start_idx = int(calendar.searchsorted(train_start_target, side="left"))
            if train_start_idx > train_end_idx:
                t_end -= pd.DateOffset(years=step_years)
                continue
            train_start = pd.Timestamp(calendar[train_start_idx])

            items.append(
                {
                    "signal_date": _fmt(signal_date),
                    "train_start": _fmt(train_start),
                    "train_end": _fmt(train_end),
                    "valid_start": _fmt(valid_start),
                    "valid_end": _fmt(valid_end),
                    "test_start": _fmt(signal_date),
                    "test_end": _fmt(test_end),
                    "pred_date": _fmt(test_end),
                }
            )

            t_end -= pd.DateOffset(years=step_years)

        # Reverse so folds are in chronological order (earliest first)
        items.reverse()
        for idx, item in enumerate(items):
            if idx + 1 < len(items):
                next_signal = pd.Timestamp(items[idx + 1]["signal_date"])
                _, oos_end = _align_right(calendar, next_signal - pd.Timedelta(days=1))
            else:
                oos_end = pd.Timestamp(item["test_end"])

            pred_date = pd.Timestamp(item["pred_date"])
            if oos_end < pred_date:
                oos_end = pred_date
            item["oos_end"] = _fmt(oos_end)

    else:
        # ── Weekly mode: walk FORWARD through weekly anchors ────────────────
        _, start_ts = _align_left(calendar, pd.Timestamp(start_date))
        anchors = _weekly_last_trade_dates(calendar)
        anchors = anchors[(anchors >= start_ts) & (anchors <= end_ts)]
        if len(anchors) <= step_weeks:
            return []

        for anchor_idx in range(0, len(anchors) - step_weeks, step_weeks):
            signal_date = pd.Timestamp(anchors[anchor_idx])
            # test_end = last trade day of the following step_weeks week(s)
            test_end = pd.Timestamp(anchors[anchor_idx + step_weeks])

            # dev window
            valid_end_idx, valid_end = _align_right(calendar, signal_date - pd.Timedelta(days=1))
            valid_start_target = signal_date - pd.DateOffset(years=valid_years)
            valid_start_idx = int(calendar.searchsorted(valid_start_target, side="left"))
            if valid_start_idx > valid_end_idx:
                continue
            valid_start = pd.Timestamp(calendar[valid_start_idx])

            # train window
            train_end_idx = valid_start_idx - 1
            if train_end_idx < 0:
                continue
            train_end = pd.Timestamp(calendar[train_end_idx])

            train_start_target = signal_date - pd.DateOffset(years=train_years + valid_years)
            if train_start_target < base_start_ts:
                continue
            train_start_idx = int(calendar.searchsorted(train_start_target, side="left"))
            if train_start_idx > train_end_idx:
                continue
            train_start = pd.Timestamp(calendar[train_start_idx])

            items.append(
                {
                    "signal_date": _fmt(signal_date),
                    "train_start": _fmt(train_start),
                    "train_end": _fmt(train_end),
                    "valid_start": _fmt(valid_start),
                    "valid_end": _fmt(valid_end),
                    "test_start": _fmt(signal_date),
                    "test_end": _fmt(test_end),
                    "pred_date": _fmt(test_end),
                    "oos_end": _fmt(test_end),
                }
            )

    return items


def _group_folds_by_year(folds: list[dict[str, str]], segment_years: int) -> list[tuple[str, list[dict[str, str]]]]:
    if segment_years <= 0:
        raise ValueError("segment_years must be positive")
    if not folds:
        return []

    first_year = pd.Timestamp(folds[0]["test_end"]).year
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for fold in folds:
        year = pd.Timestamp(fold["test_end"]).year
        seg_start = first_year + ((year - first_year) // segment_years) * segment_years
        seg_end = seg_start + segment_years - 1
        grouped[f"{seg_start}-{seg_end}"].append(fold)

    return sorted(grouped.items(), key=lambda kv: kv[0])


def _find_latest_run_dir(mlruns_root: Path, experiment_name: str | None, start_ts: float) -> Path:
    if experiment_name:
        try:
            import importlib

            mlflow = importlib.import_module("mlflow")
            mlflow.set_tracking_uri(mlruns_root.resolve().as_uri())
            experiment = mlflow.get_experiment_by_name(experiment_name)
            if experiment is not None:
                runs = mlflow.search_runs(
                    experiment_ids=[experiment.experiment_id],
                    order_by=["attributes.start_time DESC"],
                    max_results=5,
                )
                for _, row in runs.iterrows():
                    artifact_uri = str(row.get("artifact_uri", "") or "")
                    if not artifact_uri:
                        continue
                    artifact_path = Path(urlparse(artifact_uri).path)
                    pred_pkl = artifact_path / "pred.pkl"
                    if pred_pkl.exists():
                        return artifact_path.parent.resolve()
        except Exception:
            pass

    candidates: list[tuple[float, Path]] = []
    for pred_pkl in mlruns_root.glob("*/*/artifacts/pred.pkl"):
        try:
            mtime = pred_pkl.stat().st_mtime
        except FileNotFoundError:
            continue
        if mtime >= start_ts - 5:
            candidates.append((mtime, pred_pkl.parents[1].resolve()))

    if not candidates:
        raise FileNotFoundError(f"No new pred.pkl found under {mlruns_root}")
    return max(candidates, key=lambda x: (x[0], str(x[1])))[1]


def _generate_model_fold_config(
    spec: dict[str, object],
    fold: dict[str, str],
    fold_dir: Path,
    base_env: dict[str, str],
    half_life: int,
    train_base_start: str,
) -> tuple[str, Path, Path]:
    model_name = str(spec["name"])
    template_path = Path(spec["template"])
    model_mode = str(spec.get("model_mode", "default"))

    model_dir = fold_dir / "model_runs" / model_name
    model_dir.mkdir(parents=True, exist_ok=True)
    fold_config = model_dir / "workflow_config_practice.yaml"

    _run(
        [
            sys.executable,
            str(SCRIPTS / "gen_practice_yaml.py"),
            "--template",
            str(template_path),
            "--output",
            str(fold_config),
            "--model-mode",
            model_mode,
            "--data-start",
            train_base_start,
            "--sample-weight-half-life",
            str(half_life),
            "--train-start",
            fold["train_start"],
            "--train-end",
            fold["train_end"],
            "--valid-start",
            fold["valid_start"],
            "--valid-end",
            fold["valid_end"],
            "--test-start",
            fold["test_start"],
            "--test-end",
            fold["oos_end"],
        ],
        cwd=ROOT,
        env=base_env,
    )

    return model_name, model_dir, fold_config


def _train_single_model_fold(
    spec: dict[str, object],
    fold: dict[str, str],
    fold_dir: Path,
    mlruns_root: Path,
    base_env: dict[str, str],
    uri_folder: str,
    experiment_name: str,
    half_life: int,
    floor: float,
    train_base_start: str,
    warm_start_checkpoint: Path | None = None,
) -> tuple[Path, str]:
    model_name, model_dir, fold_config = _generate_model_fold_config(
        spec=spec,
        fold=fold,
        fold_dir=fold_dir,
        base_env=base_env,
        half_life=half_life,
        train_base_start=train_base_start,
    )

    existing_run_dir = model_dir / "mlflow_run"
    existing_artifacts = existing_run_dir / "artifacts"
    required_artifacts = [
        existing_artifacts / "pred.pkl",
        existing_artifacts / "label.pkl",
        existing_artifacts / "valid_pred.pkl",
        existing_artifacts / "valid_label.pkl",
        existing_artifacts / "params.pkl",
    ]
    if all(path.exists() for path in required_artifacts):
        print(f"      reuse cached run: {model_name} -> {existing_run_dir}")
        return existing_run_dir, f"{experiment_name}_wf_{fold['signal_date']}_{model_name}"

    experiment_tag = f"{experiment_name}_wf_{fold['signal_date']}_{model_name}"
    start_ts = time.time()
    if warm_start_checkpoint is not None:
        print(f"      warm-start: {model_name} <- {warm_start_checkpoint}")
    else:
        print(f"      warm-start: {model_name} <- <none>")
    _run(
        [
            sys.executable,
            str(SCRIPTS / "run_stage2_practice.py"),
            "--config",
            str(fold_config),
            "--experiment-name",
            experiment_tag,
            "--uri-folder",
            uri_folder,
            "--half-life",
            str(half_life),
            "--floor",
            str(floor),
            *(["--warm-start", str(warm_start_checkpoint)] if warm_start_checkpoint is not None else []),
        ],
        cwd=ROOT,
        env=base_env,
    )

    run_dir = _find_latest_run_dir(
        mlruns_root=mlruns_root,
        experiment_name=experiment_tag,
        start_ts=start_ts,
    )
    model_run_dir = model_dir / "mlflow_run"
    if model_run_dir.exists():
        shutil.rmtree(model_run_dir)
    shutil.copytree(run_dir, model_run_dir)
    try:
        shutil.rmtree(run_dir)
    except Exception:
        pass
    return model_run_dir, experiment_tag


def _build_ensemble_fold_output(
    fold: dict[str, str],
    fold_dir: Path,
    fold_output: Path,
    mlruns_root: Path,
    template_cfg: dict,
    base_env: dict[str, str],
    args: argparse.Namespace,
    previous_checkpoints: dict[str, Path],
) -> dict[str, object]:
    model_artifacts: dict[str, Path] = {}
    validation_ics: dict[str, float] = {}
    test_preds: dict[str, pd.DataFrame] = {}
    label_frames: dict[str, pd.DataFrame] = {}

    print(f"  → sequential base models: {', '.join(str(spec['name']) for spec in MODEL_SPECS)}")
    for spec in MODEL_SPECS:
        model_name = str(spec["name"])
        print(f"    · training {model_name}")
        model_run_dir, _ = _train_single_model_fold(
            spec=spec,
            fold=fold,
            fold_dir=fold_dir,
            mlruns_root=mlruns_root,
            base_env=base_env,
            uri_folder=args.uri_folder,
            experiment_name=args.experiment_name,
            half_life=args.half_life,
            floor=args.floor,
            train_base_start=args.train_base_start,
            warm_start_checkpoint=previous_checkpoints.get(model_name),
        )
        model_artifacts[model_name] = model_run_dir
        artifacts = model_run_dir / "artifacts"

        valid_pred = _to_score_frame(_load_pickle(artifacts / "valid_pred.pkl"), "score")
        valid_label = _to_label_frame(_load_pickle(artifacts / "valid_label.pkl"))
        _, ic_mean, _ = _compute_daily_ic(valid_pred, valid_label)
        validation_ics[model_name] = ic_mean

        test_preds[model_name] = _to_score_frame(_load_pickle(artifacts / "pred.pkl"), "score")
        label_frames[model_name] = _to_label_frame(_load_pickle(artifacts / "label.pkl"))

    target_names = _target_route_model_names()
    label_df = None
    for model_name in target_names:
        if model_name in label_frames:
            label_df = label_frames[model_name]
            break
    if label_df is None and label_frames:
        label_df = next(iter(label_frames.values()))

    if label_df is None:
        raise RuntimeError("No test label data found for ensemble fold")

    weights = _compute_ensemble_weights(validation_ics)
    print(f"  → validation IC weights: {weights}")
    ensemble_pred = _combine_model_predictions(test_preds, weights)
    strategy_metrics = _compute_strategy_metrics(ensemble_pred[["score"]], label_df, args.hold_num)

    ensemble_run_dir = fold_dir / "ensemble_run"
    if ensemble_run_dir.exists():
        shutil.rmtree(ensemble_run_dir)
    _build_synthetic_run_dir(
        ensemble_run_dir=ensemble_run_dir,
        pred_df=ensemble_pred[["score"]],
        label_df=label_df[["label"]],
        validation_ics=validation_ics,
        weights=weights,
    )
    _export_fold_outputs(ensemble_run_dir, fold_output, fold["pred_date"], base_env)
    fold_metrics = _augment_exported_scores(
        fold_output=fold_output,
        pred_date=fold["pred_date"],
        weights=weights,
        validation_ics=validation_ics,
        strategy_metrics=strategy_metrics,
    )

    (fold_output / "ensemble_metadata.json").write_text(
        json.dumps(
            {
                "pred_date": fold["pred_date"],
                "validation_ic": validation_ics,
                "weights": weights,
                "strategy_metrics": strategy_metrics,
                "models": [spec["name"] for spec in MODEL_SPECS],
                "warm_start_strategy": WARM_START_STRATEGY,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return fold_metrics


def _export_fold_outputs(fold_run_dir: Path, fold_output: Path, pred_date: str, env: dict[str, str]) -> None:
    _run(
        [
            sys.executable,
            str(SCRIPTS / "export_model_predict.py"),
            "--run-dir",
            str(fold_run_dir),
            "--output",
            str(fold_output),
            "--pred-date",
            pred_date,
        ],
        cwd=ROOT,
        env=env,
    )


def _fold_output_ready(fold_output: Path) -> bool:
    required = ["scores.csv", "metrics.csv", "overview.html"]
    return all((fold_output / name).exists() for name in required)


def _fold_output_matches_window(fold_output: Path, pred_date: str, oos_end: str) -> bool:
    if not _fold_output_ready(fold_output):
        return False

    scores_csv = fold_output / "scores.csv"
    all_scores_csv = fold_output / "all_scores.csv"
    if not scores_csv.exists() or not all_scores_csv.exists():
        return False

    metadata_json = fold_output / "ensemble_metadata.json"
    expected_models = [spec["name"] for spec in MODEL_SPECS]
    if metadata_json.exists():
        try:
            metadata = json.loads(metadata_json.read_text(encoding="utf-8"))
            actual_models = metadata.get("models")
            if actual_models is not None and list(actual_models) != expected_models:
                return False
            if metadata.get("warm_start_strategy") != WARM_START_STRATEGY:
                return False
        except Exception:
            return False

    try:
        scores_df = pd.read_csv(scores_csv, usecols=lambda c: c in {"pred_date"})
        if scores_df.empty or "pred_date" not in scores_df.columns:
            return False
        score_pred_date = str(scores_df["pred_date"].dropna().astype(str).iloc[0])
        if score_pred_date != pred_date:
            return False

        all_scores_df = pd.read_csv(all_scores_csv, usecols=lambda c: c in {"datetime"})
        if all_scores_df.empty or "datetime" not in all_scores_df.columns:
            return False
        max_dt = pd.to_datetime(all_scores_df["datetime"], errors="coerce").dropna().max()
        if pd.isna(max_dt):
            return False
        return max_dt >= pd.Timestamp(oos_end)
    except Exception:
        return False


def _copy_fold_outputs(src_dir: Path, dst_dir: Path) -> None:
    dst_dir.mkdir(parents=True, exist_ok=True)
    for name in ["scores.csv", "metrics.csv", "overview.html", "all_scores.csv", "ensemble_metadata.json"]:
        src = src_dir / name
        if src.exists():
            shutil.copy2(src, dst_dir / name)


def _generate_summary(fold_rows: list[dict[str, object]], output_root: Path) -> None:
    if not fold_rows:
        return

    fold_df = pd.DataFrame(fold_rows)
    fold_csv = output_root / "walk_forward_folds.csv"
    fold_df.to_csv(fold_csv, index=False, encoding="utf-8-sig")

    ic_source = fold_df["IC_mean"] if "IC_mean" in fold_df else pd.Series(dtype=float)
    ic_series = pd.to_numeric(ic_source, errors="coerce").dropna()
    ic_mean = float(ic_series.mean()) if not ic_series.empty else np.nan
    ic_std = float(ic_series.std(ddof=1)) if len(ic_series) > 1 else np.nan
    ic_t_stat = (
        float(ic_mean / (ic_std / np.sqrt(len(ic_series))))
        if len(ic_series) > 1 and pd.notna(ic_std) and ic_std > 0
        else np.nan
    )
    skipped_count = int(fold_df["skipped"].fillna(False).astype(bool).sum()) if "skipped" in fold_df else 0
    executed_count = int(len(fold_df) - skipped_count)
    available_count = int(len(fold_df))

    metric_cols = [
        c
        for c in fold_df.columns
        if pd.api.types.is_numeric_dtype(fold_df[c]) and c not in {"fold"}
    ]
    summary_rows = []
    for metric in metric_cols:
        series = pd.to_numeric(fold_df[metric], errors="coerce").dropna()
        summary_rows.append(
            {
                "metric": metric,
                "mean": float(series.mean()) if not series.empty else np.nan,
                "std": float(series.std()) if not series.empty else np.nan,
                "min": float(series.min()) if not series.empty else np.nan,
                "max": float(series.max()) if not series.empty else np.nan,
                "last": float(series.iloc[-1]) if not series.empty else np.nan,
            }
        )
    summary_rows.extend(
        [
            {"metric": "fold_count", "mean": float(available_count), "std": np.nan, "min": np.nan, "max": np.nan, "last": float(available_count)},
            {"metric": "available_fold_count", "mean": float(available_count), "std": np.nan, "min": np.nan, "max": np.nan, "last": float(available_count)},
            {"metric": "executed_fold_count", "mean": float(executed_count), "std": np.nan, "min": np.nan, "max": np.nan, "last": float(executed_count)},
            {"metric": "cached_fold_count", "mean": float(skipped_count), "std": np.nan, "min": np.nan, "max": np.nan, "last": float(skipped_count)},
            {"metric": "IC_mean_t_stat", "mean": ic_t_stat, "std": np.nan, "min": np.nan, "max": np.nan, "last": ic_t_stat},
        ]
    )
    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(output_root / "walk_forward_summary.csv", index=False, encoding="utf-8-sig")

    # Simple human-readable report for quick inspection.
    report_lines = [
        "Walk-forward Stage2 Summary",
        "===========================",
        f"Available folds: {available_count}",
        f"Executed folds this run: {executed_count}",
        f"Resumed cached folds: {skipped_count}",
        f"IC mean: {ic_mean:.6f}" if pd.notna(ic_mean) else "IC mean: N/A",
        f"IC t-stat: {ic_t_stat:.6f}" if pd.notna(ic_t_stat) else "IC t-stat: N/A",
        "",
        "Per-fold metrics (top rows):",
        fold_df.head(20).to_string(index=False),
        "",
        "Aggregate metrics:",
        summary_df.to_string(index=False),
        "",
    ]
    (output_root / "walk_forward_summary.txt").write_text("\n".join(report_lines), encoding="utf-8")


def _load_fold_scores(fold_output: Path) -> pd.DataFrame:
    """Load per-fold prediction scores for full-cycle backtest aggregation.

    Prefers all_scores.csv (all test-period dates) over scores.csv (single
    snapshot date).  all_scores.csv is written by export_model_predict.py
    when pred.pkl contains multiple trading days (annual mode).
    """
    all_scores_csv = fold_output / "all_scores.csv"
    scores_csv = fold_output / "scores.csv"
    csv_path = all_scores_csv if all_scores_csv.exists() else scores_csv
    if not csv_path.exists():
        return pd.DataFrame()

    df = pd.read_csv(csv_path)
    if df.empty:
        return df

    # Normalise column names: accept both 'pred_date' and 'datetime'
    date_col = next((c for c in ["datetime", "pred_date"] if c in df.columns), None)
    if date_col is None or "instrument" not in df.columns or "score" not in df.columns:
        return pd.DataFrame()

    out = df[[date_col, "instrument", "score"]].copy()
    out["datetime"] = pd.to_datetime(out[date_col])
    out = out[["datetime", "instrument", "score"]]
    out["score"] = pd.to_numeric(out["score"], errors="coerce")
    out = out.dropna(subset=["datetime", "instrument", "score"])
    return out


def _build_full_signal(fold_outputs: list[Path]) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for fold_output in fold_outputs:
        df = _load_fold_scores(fold_output)
        if not df.empty:
            frames.append(df)

    if not frames:
        return pd.DataFrame(columns=["score"])

    signal_df = pd.concat(frames, ignore_index=True)
    signal_df = signal_df.drop_duplicates(subset=["datetime", "instrument"], keep="last")
    signal_df = signal_df.sort_values(["datetime", "instrument"])
    signal_df = signal_df.set_index(["datetime", "instrument"])[["score"]]
    signal_df.index = signal_df.index.set_names(["datetime", "instrument"])
    return signal_df


def _backtest_metrics_from_report(report_df: pd.DataFrame) -> dict[str, float]:
    if report_df is None or report_df.empty:
        return {
            "annualized_return": float("nan"),
            "max_drawdown": float("nan"),
            "sharpe_ratio": float("nan"),
            "information_ratio": float("nan"),
            "monthly_win_rate": float("nan"),
            "turnover_mean": float("nan"),
            "turnover_sum": float("nan"),
        }

    rpt = report_df.copy()
    rpt.index = pd.to_datetime(rpt.index)
    for col in ["return", "cost", "bench", "turnover"]:
        if col not in rpt.columns:
            rpt[col] = 0.0
        rpt[col] = pd.to_numeric(rpt[col], errors="coerce").fillna(0.0)

    strategy_ret = rpt["return"] - rpt["cost"]
    excess_ret = strategy_ret - rpt["bench"]
    n = len(strategy_ret)
    annualized_return = float((1 + strategy_ret).prod() ** (252 / max(n, 1)) - 1) if n else float("nan")
    equity = (1 + strategy_ret).cumprod()
    max_drawdown = float((equity / equity.cummax() - 1).min()) if n else float("nan")
    sharpe = float(strategy_ret.mean() / strategy_ret.std(ddof=1) * np.sqrt(252)) if strategy_ret.std(ddof=1) > 0 else float("nan")
    ir = float(excess_ret.mean() / excess_ret.std(ddof=1) * np.sqrt(252)) if excess_ret.std(ddof=1) > 0 else float("nan")
    monthly = (1 + strategy_ret).resample("ME").prod() - 1 if n else pd.Series(dtype=float)

    return {
        "annualized_return": annualized_return,
        "max_drawdown": max_drawdown,
        "sharpe_ratio": sharpe,
        "information_ratio": ir,
        "monthly_win_rate": float((monthly > 0).mean()) if not monthly.empty else float("nan"),
        "turnover_mean": float(rpt["turnover"].mean()),
        "turnover_sum": float(rpt["turnover"].sum()),
    }


def _signal_coverage_diagnostics(trade_signal: pd.DataFrame, calendar: pd.DatetimeIndex) -> dict[str, float]:
    if trade_signal.empty:
        return {
            "trade_signal_dates": 0.0,
            "calendar_days": 0.0,
            "signal_coverage_ratio": float("nan"),
            "median_gap_days": float("nan"),
            "max_gap_days": float("nan"),
        }

    signal_dates = pd.DatetimeIndex(pd.to_datetime(trade_signal.index.get_level_values("datetime")).unique()).sort_values()
    calendar_slice = calendar[(calendar >= signal_dates.min()) & (calendar <= signal_dates.max())]
    coverage_ratio = float(len(signal_dates) / len(calendar_slice)) if len(calendar_slice) else float("nan")

    if len(signal_dates) > 1:
        calendar_pos = calendar.get_indexer(signal_dates)
        gap_sizes = np.diff(calendar_pos)
        median_gap_days = float(np.median(gap_sizes))
        max_gap_days = float(np.max(gap_sizes))
    else:
        median_gap_days = float("nan")
        max_gap_days = float("nan")

    return {
        "trade_signal_dates": float(len(signal_dates)),
        "calendar_days": float(len(calendar_slice)),
        "signal_coverage_ratio": coverage_ratio,
        "median_gap_days": median_gap_days,
        "max_gap_days": max_gap_days,
    }


def _fold_pred_date(fold_output: Path) -> str | None:
    scores_csv = fold_output / "scores.csv"
    if not scores_csv.exists():
        return None
    try:
        df = pd.read_csv(scores_csv, usecols=lambda c: c in {"pred_date", "date"})
    except Exception:
        return None
    for col in ["pred_date", "date"]:
        if col in df.columns and not df[col].dropna().empty:
            return str(df[col].dropna().astype(str).iloc[0])
    return None


def _stage36_replay_signal_from_fold(
    fold_output: Path,
    replay_dir: Path,
    pred_date: str,
    hold_num: int,
) -> pd.DataFrame:
    """Replay stage3~stage6 for one fold and convert the final portfolio into a trade signal."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from scripts.practice.stage3_first_screen import first_screen
    from scripts.practice.stage4_risk_eval import risk_eval
    from scripts.practice.stage5_second_screen import second_screen
    from scripts.practice.stage6_final_result import final_result

    replay_dir.mkdir(parents=True, exist_ok=True)
    stage3_dir = replay_dir / "stage3_first_screen"
    stage4_dir = replay_dir / "stage4_risk_eval"
    stage5_dir = replay_dir / "stage5_second_screen"
    stage6_dir = replay_dir / "stage6_final_result"

    # Run the downstream chain directly through callable functions.
    first_screen(str(fold_output), str(stage3_dir), pred_date, top_n=20, max_price=float(os.environ.get("MAX_STOCK_PRICE", 50.0)))
    risk_eval(str(stage3_dir / "first_screen.csv"), str(stage4_dir), pred_date)
    second_screen(str(stage4_dir / "risk_eval.csv"), str(fold_output), str(stage5_dir), hold_num=hold_num)
    final_result(str(stage5_dir / "second_screen.csv"), str(fold_output), str(stage6_dir), hold_num=hold_num)

    result_update_csv = stage6_dir / "result_update.csv"
    if not result_update_csv.exists():
        raise FileNotFoundError(f"stage6 replay did not produce result_update.csv under {stage6_dir}")

    result_update = pd.read_csv(result_update_csv)
    if result_update.empty:
        return pd.DataFrame(columns=["score"])
    if "code" not in result_update.columns:
        raise RuntimeError(f"stage6 replay output missing code column: {result_update_csv}")

    score_col = "weight" if "weight" in result_update.columns else None
    if score_col is None:
        score_col = "risk_parity_weight" if "risk_parity_weight" in result_update.columns else None
    if score_col is None:
        score_col = "score" if "score" in result_update.columns else None
    if score_col is None:
        result_update["score"] = 1.0
        score_col = "score"

    trade_dt = pd.to_datetime(pred_date)
    out = result_update.copy()
    out["datetime"] = trade_dt
    out["instrument"] = out["code"].astype(str)
    out["score"] = pd.to_numeric(out[score_col], errors="coerce").fillna(0.0)
    out = out[["datetime", "instrument", "score"]].dropna(subset=["datetime", "instrument", "score"])
    return out


def _build_stage36_full_signal(
    fold_outputs: list[Path],
    output_root: Path,
    hold_num: int,
) -> pd.DataFrame:
    """Build a replay signal from stage3~stage6 outputs on each fold."""
    replay_root = output_root / "full_backtest" / "stage36_replay"
    frames: list[pd.DataFrame] = []

    for fold_output in fold_outputs:
        pred_date = _fold_pred_date(fold_output)
        if not pred_date:
            continue
        fold_tag = fold_output.parent.name
        replay_dir = replay_root / fold_tag
        try:
            df = _stage36_replay_signal_from_fold(
                fold_output=fold_output,
                replay_dir=replay_dir,
                pred_date=pred_date,
                hold_num=hold_num,
            )
        except Exception as exc:
            print(f"  ⚠ stage3~stage6 replay failed for fold {fold_tag}: {exc}")
            continue
        if not df.empty:
            frames.append(df)

    if not frames:
        return pd.DataFrame(columns=["score"])

    signal_df = pd.concat(frames, ignore_index=True)
    signal_df = signal_df.drop_duplicates(subset=["datetime", "instrument"], keep="last")
    signal_df = signal_df.sort_values(["datetime", "instrument"])
    signal_df = signal_df.set_index(["datetime", "instrument"])[["score"]]
    signal_df.index = signal_df.index.set_names(["datetime", "instrument"])
    return signal_df


def _get_price_cap() -> float:
    return float(os.environ.get("MAX_STOCK_PRICE", 50.0) or 50.0)


def _shift_signal_to_next_trade_dates(signal_df: pd.DataFrame, cal: pd.DatetimeIndex) -> pd.DataFrame:
    """Keep one signal per ISO week and shift it to the next trading day."""
    if signal_df.empty:
        return signal_df

    df = signal_df.reset_index().copy()
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    df["instrument"] = df["instrument"].astype(str)
    keep_cols = [c for c in df.columns if c not in {"datetime", "instrument"}]
    for col in keep_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    required_cols = ["datetime", "instrument"] + (["score"] if "score" in df.columns else [])
    df = df.dropna(subset=required_cols)
    if df.empty:
        return signal_df.iloc[0:0]

    weekly_dates = (
        df[["datetime"]]
        .drop_duplicates()
        .assign(
            iso_year=lambda x: pd.to_datetime(x["datetime"]).dt.isocalendar().year,
            iso_week=lambda x: pd.to_datetime(x["datetime"]).dt.isocalendar().week,
        )
        .groupby(["iso_year", "iso_week"], as_index=False)["datetime"]
        .max()["datetime"]
    )
    df = df[df["datetime"].isin(set(pd.to_datetime(weekly_dates)))]
    if df.empty:
        return signal_df.iloc[0:0]

    trade_dates = []
    for dt in pd.to_datetime(df["datetime"]):
        pos = int(cal.searchsorted(dt, side="right"))
        trade_dates.append(pd.Timestamp(cal[pos]) if pos < len(cal) else pd.NaT)

    df["trade_datetime"] = trade_dates
    df = df.dropna(subset=["trade_datetime"])
    if df.empty:
        return signal_df.iloc[0:0]

    df = df.drop(columns=["datetime"]).rename(columns={"trade_datetime": "datetime"})
    df = df.drop_duplicates(subset=["datetime", "instrument"], keep="last")
    df = df.sort_values(["datetime", "instrument"])
    shifted = df.set_index(["datetime", "instrument"])[keep_cols]
    shifted.index = shifted.index.set_names(["datetime", "instrument"])
    return shifted


def _build_buffered_equal_weight_signal(
    signal_df: pd.DataFrame,
    cal: pd.DatetimeIndex,
    hold_num: int,
    price_cap: float,
    dropout_buffer_pct: float = 0.5,
) -> pd.DataFrame:
    """Build a live-aligned Top-K portfolio with a global-rank buffer and equal target weights.

    Rules:
    1. Use raw stage2 score ranking as the selection source.
    2. Hold at most `hold_num` stocks.
    3. Existing holdings are kept if they remain within the top
         `dropout_buffer_pct` fraction of the whole cross-sectional universe.
         For example, with a csi1000 universe and dropout_buffer_pct=0.5,
         holdings are only sold after they fall out of roughly the top 500 names.
    4. Vacancies are filled by the highest-score affordable stocks.
    5. Final target weights are equal-weighted across the selected holdings.
    """
    if signal_df.empty:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    from qlib.data import D

    shifted_signal = _shift_signal_to_next_trade_dates(signal_df[["score"]], cal)
    if shifted_signal.empty:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    shifted_df = shifted_signal.reset_index().copy()
    shifted_df["datetime"] = pd.to_datetime(shifted_df["datetime"], errors="coerce")
    shifted_df["instrument"] = shifted_df["instrument"].astype(str)
    shifted_df["score"] = pd.to_numeric(shifted_df["score"], errors="coerce")
    shifted_df = shifted_df.dropna(subset=["datetime", "instrument", "score"])
    if shifted_df.empty:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    instruments = sorted(shifted_df["instrument"].unique().tolist())
    start_time = pd.Timestamp(shifted_df["datetime"].min()).strftime("%Y-%m-%d")
    end_time = pd.Timestamp(shifted_df["datetime"].max()).strftime("%Y-%m-%d")
    close_df = D.features(instruments, ["$close"], start_time=start_time, end_time=end_time)
    if close_df is None or len(close_df) == 0:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    if isinstance(close_df, pd.Series):
        close_df = close_df.to_frame("close")
    else:
        close_df = close_df.copy()
    if isinstance(close_df.index, pd.MultiIndex):
        close_df = close_df.reset_index()
    if "datetime" not in close_df.columns or "instrument" not in close_df.columns:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    close_col = "close" if "close" in close_df.columns else close_df.columns[-1]
    close_df["datetime"] = pd.to_datetime(close_df["datetime"], errors="coerce")
    close_df["instrument"] = close_df["instrument"].astype(str)
    close_df[close_col] = pd.to_numeric(close_df[close_col], errors="coerce")
    close_df = close_df[["datetime", "instrument", close_col]].dropna()
    close_df = close_df.rename(columns={close_col: "close"})

    ranked = shifted_df.merge(close_df, on=["datetime", "instrument"], how="left")
    ranked["close"] = pd.to_numeric(ranked["close"], errors="coerce")
    ranked["is_affordable"] = ranked["close"].notna() & (ranked["close"] <= float(price_cap))

    prev_holdings: list[str] = []
    frames: list[pd.DataFrame] = []

    for dt, grp in ranked.groupby("datetime", sort=True):
        grp = grp.sort_values(["score", "instrument"], ascending=[False, True], na_position="last").reset_index(drop=True)
        if grp.empty:
            continue
        grp["rank"] = np.arange(1, len(grp) + 1)
        keep_rank_cutoff = max(int(hold_num), int(np.ceil(len(grp) * max(float(dropout_buffer_pct), 0.0))))
        affordable = grp[grp["is_affordable"]].copy().reset_index(drop=True)
        if affordable.empty:
            prev_holdings = []
            continue

        rank_map = affordable.set_index("instrument")["rank"].to_dict()
        kept = [
            code
            for code in prev_holdings
            if code in rank_map and int(rank_map[code]) <= keep_rank_cutoff
        ]
        kept = sorted(kept, key=lambda code: (int(rank_map.get(code, 10**9)), code))[:hold_num]

        additions = [code for code in affordable["instrument"].tolist() if code not in kept]
        target_codes = kept + additions[: max(int(hold_num) - len(kept), 0)]
        if not target_codes:
            prev_holdings = []
            continue

        selected = affordable.set_index("instrument").loc[target_codes].reset_index()
        selected["selected"] = np.where(selected["instrument"].isin(kept), "keep", "buy")
        selected["weight"] = 1.0 / float(len(selected))
        selected["datetime"] = pd.Timestamp(dt)
        frames.append(selected[["datetime", "instrument", "score", "weight", "rank", "close", "selected"]])
        prev_holdings = list(target_codes)

    if not frames:
        return pd.DataFrame(columns=["score", "weight", "rank", "close", "selected"])

    out = pd.concat(frames, ignore_index=True)
    out = out.drop_duplicates(subset=["datetime", "instrument"], keep="last")
    out = out.sort_values(["datetime", "rank", "instrument"])
    out = out.set_index(["datetime", "instrument"])[["score", "weight", "rank", "close", "selected"]]
    out.index = out.index.set_names(["datetime", "instrument"])
    return out


def _build_risk_parity_signal_from_raw_signal(
    signal_df: pd.DataFrame,
    hold_num: int,
    lookback_days: int = 60,
    score_mix: float = 0.7,
    vol_mix: float = 0.3,
) -> pd.DataFrame:
    """Convert raw stage2 scores into a weighted signal using a Risk-Parity style blend.

    The target weight is built from two components:
    1. cross-sectional normalized score strength
    2. inverse-volatility allocation over the selected Top-K names

    This is used as a fallback when the full stage3~stage6 replay signal is not
    available, so the stage2 backtest is still closer to the live portfolio
    construction logic than a plain equal-weight TopK replay.
    """
    if signal_df.empty:
        return pd.DataFrame(columns=["score", "weight", "volatility_60d"])

    from qlib.data import D

    df = signal_df.reset_index().copy()
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    df["instrument"] = df["instrument"].astype(str)
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    df = df.dropna(subset=["datetime", "instrument", "score"])
    if df.empty:
        return pd.DataFrame(columns=["score", "weight", "volatility_60d"])

    instruments = sorted(df["instrument"].unique().tolist())
    start_time = (pd.Timestamp(df["datetime"].min()) - pd.Timedelta(days=lookback_days * 3)).strftime("%Y-%m-%d")
    end_time = pd.Timestamp(df["datetime"].max()).strftime("%Y-%m-%d")
    close_df = D.features(instruments, ["$close"], start_time=start_time, end_time=end_time)

    close_map: dict[str, pd.Series] = {}
    if close_df is not None and len(close_df) > 0:
        if isinstance(close_df, pd.Series):
            close_df = close_df.to_frame("close")
        else:
            close_df = close_df.copy()
        if isinstance(close_df.index, pd.MultiIndex):
            close_df = close_df.reset_index()
        if "datetime" in close_df.columns and "instrument" in close_df.columns:
            close_col = "close" if "close" in close_df.columns else close_df.columns[-1]
            close_df["datetime"] = pd.to_datetime(close_df["datetime"], errors="coerce")
            close_df["instrument"] = close_df["instrument"].astype(str)
            close_df[close_col] = pd.to_numeric(close_df[close_col], errors="coerce")
            close_df = close_df[["datetime", "instrument", close_col]].dropna()
            close_df = close_df.rename(columns={close_col: "close"})
            close_df = close_df.sort_values(["instrument", "datetime"])
            close_df["ret"] = close_df.groupby("instrument")["close"].pct_change()
            close_map = {
                inst: grp.set_index("datetime")["ret"].sort_index() for inst, grp in close_df.groupby("instrument")
            }

    frames: list[pd.DataFrame] = []
    for dt, grp in df.groupby("datetime", sort=True):
        pick = grp.sort_values("score", ascending=False).head(max(int(hold_num), 1)).copy()
        if pick.empty:
            continue

        score_values = pd.to_numeric(pick["score"], errors="coerce")
        if score_values.notna().sum() <= 1:
            score_weight = pd.Series(1.0 / len(pick), index=pick.index, dtype=float)
        else:
            lo, hi = float(score_values.min()), float(score_values.max())
            if hi > lo:
                score_weight = ((score_values - lo) / (hi - lo)).fillna(0.0)
                if float(score_weight.sum()) <= 0:
                    score_weight = pd.Series(1.0 / len(pick), index=pick.index, dtype=float)
                else:
                    score_weight = score_weight / float(score_weight.sum())
            else:
                score_weight = pd.Series(1.0 / len(pick), index=pick.index, dtype=float)

        vols = []
        for inst in pick["instrument"].astype(str):
            ret_s = close_map.get(inst)
            if ret_s is None or ret_s.empty:
                vols.append(np.nan)
                continue
            hist = ret_s[ret_s.index < dt].dropna().tail(lookback_days)
            if len(hist) < 5:
                vols.append(np.nan)
            else:
                vols.append(float(hist.std(ddof=1)))
        pick["volatility_60d"] = vols

        inv_vol = 1.0 / pd.to_numeric(pick["volatility_60d"], errors="coerce").replace(0, np.nan)
        inv_vol = inv_vol.replace([np.inf, -np.inf], np.nan)
        if inv_vol.notna().sum() == 0:
            vol_weight = pd.Series(1.0 / len(pick), index=pick.index, dtype=float)
        else:
            fill_value = float(inv_vol.dropna().median()) if inv_vol.notna().any() else 1.0
            inv_vol = inv_vol.fillna(fill_value)
            vol_weight = inv_vol / float(inv_vol.sum())

        combined = score_mix * score_weight + vol_mix * vol_weight
        if combined.isna().all() or float(combined.sum()) <= 0:
            combined = pd.Series(1.0 / len(pick), index=pick.index, dtype=float)
        else:
            combined = combined.fillna(0.0)
            combined = combined / float(combined.sum())

        pick["weight"] = combined.astype(float)
        frames.append(pick[["datetime", "instrument", "score", "weight", "volatility_60d"]])

    if not frames:
        return pd.DataFrame(columns=["score", "weight", "volatility_60d"])

    out = pd.concat(frames, ignore_index=True)
    out = out.drop_duplicates(subset=["datetime", "instrument"], keep="last")
    out = out.sort_values(["datetime", "instrument"])
    out = out.set_index(["datetime", "instrument"])[["score", "weight", "volatility_60d"]]
    out.index = out.index.set_names(["datetime", "instrument"])
    return out


class PrecomputedWeightStrategy:
    """Factory wrapper around Qlib WeightStrategyBase for precomputed target weights."""

    @staticmethod
    def create(signal, risk_degree: float = 0.95):
        from qlib.contrib.strategy.order_generator import OrderGenWOInteract
        from qlib.contrib.strategy.signal_strategy import WeightStrategyBase

        class _RedistributingOrderGenWOInteract(OrderGenWOInteract):
            """Redistribute dropped non-tradable buy weights to tradable targets on trade date."""

            def generate_order_list_from_target_weight_position(
                self,
                current,
                trade_exchange,
                target_weight_position,
                risk_degree,
                pred_start_time,
                pred_end_time,
                trade_start_time,
                trade_end_time,
            ):
                if target_weight_position is None:
                    return []

                clean_target = {
                    str(stock_id): float(weight)
                    for stock_id, weight in dict(target_weight_position).items()
                    if pd.notna(weight) and float(weight) > 0
                }
                if not clean_target:
                    return []

                current_stock = set(current.get_stock_list())
                tradable_target: dict[str, float] = {}
                locked_target: dict[str, float] = {}

                for stock_id, weight in clean_target.items():
                    trade_tradable = trade_exchange.is_stock_tradable(
                        stock_id=stock_id,
                        start_time=trade_start_time,
                        end_time=trade_end_time,
                    )
                    pred_tradable = trade_exchange.is_stock_tradable(
                        stock_id=stock_id,
                        start_time=pred_start_time,
                        end_time=pred_end_time,
                    )
                    if trade_tradable and pred_tradable:
                        tradable_target[stock_id] = weight
                    elif stock_id in current_stock:
                        locked_target[stock_id] = weight

                if tradable_target:
                    tradable_weight_sum = float(sum(tradable_target.values()))
                    locked_weight_sum = float(sum(locked_target.values()))
                    residual_weight = max(1.0 - locked_weight_sum, 0.0)
                    if tradable_weight_sum > 0 and residual_weight > 0:
                        tradable_target = {
                            stock_id: weight / tradable_weight_sum * residual_weight
                            for stock_id, weight in tradable_target.items()
                        }

                adjusted_target = {**locked_target, **tradable_target}
                total_weight = float(sum(adjusted_target.values()))
                if total_weight <= 0:
                    return []
                adjusted_target = {stock_id: weight / total_weight for stock_id, weight in adjusted_target.items()}

                return super().generate_order_list_from_target_weight_position(
                    current=current,
                    trade_exchange=trade_exchange,
                    target_weight_position=adjusted_target,
                    risk_degree=risk_degree,
                    pred_start_time=pred_start_time,
                    pred_end_time=pred_end_time,
                    trade_start_time=trade_start_time,
                    trade_end_time=trade_end_time,
                )

        class _PrecomputedWeightStrategy(WeightStrategyBase):
            def __init__(self, **kwargs):
                super().__init__(order_generator_cls_or_obj=_RedistributingOrderGenWOInteract(), **kwargs)

            def generate_target_weight_position(self, score, current, trade_start_time, trade_end_time):
                if score is None:
                    return {}
                if isinstance(score, pd.Series):
                    weight_s = pd.to_numeric(score, errors="coerce")
                else:
                    score = score.copy()
                    if "weight" in score.columns:
                        weight_s = pd.to_numeric(score["weight"], errors="coerce")
                    elif "risk_parity_weight" in score.columns:
                        weight_s = pd.to_numeric(score["risk_parity_weight"], errors="coerce")
                    elif "score" in score.columns:
                        weight_s = pd.to_numeric(score["score"], errors="coerce")
                    else:
                        weight_s = pd.to_numeric(score.iloc[:, 0], errors="coerce")
                weight_s = weight_s.replace([np.inf, -np.inf], np.nan).dropna()
                weight_s = weight_s[weight_s > 0]
                if weight_s.empty:
                    return {}
                total = float(weight_s.sum())
                if total <= 0:
                    return {}
                weight_s = weight_s / total
                return {str(k): float(v) for k, v in weight_s.items() if pd.notna(v) and v > 0}

        return _PrecomputedWeightStrategy(signal=signal, risk_degree=risk_degree)


RiskParityWeightStrategy = PrecomputedWeightStrategy


def _apply_price_cap_to_trade_signal(trade_signal: pd.DataFrame, price_cap: float = 50.0) -> pd.DataFrame:
    """Exclude instruments whose close price is above the cap on the trade date."""
    if trade_signal.empty:
        return trade_signal

    from qlib.data import D

    value_cols = [c for c in trade_signal.columns]
    df = trade_signal.reset_index().copy()
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    df["instrument"] = df["instrument"].astype(str)
    if "score" in df.columns:
        df["score"] = pd.to_numeric(df["score"], errors="coerce")
    for col in value_cols:
        if col != "volatility_60d":
            df[col] = pd.to_numeric(df[col], errors="coerce")
    required_cols = ["datetime", "instrument"] + (["score"] if "score" in df.columns else [])
    df = df.dropna(subset=required_cols)
    if df.empty:
        return trade_signal.iloc[0:0]

    instruments = sorted(df["instrument"].astype(str).unique().tolist())
    start_time = pd.Timestamp(df["datetime"].min()).strftime("%Y-%m-%d")
    end_time = pd.Timestamp(df["datetime"].max()).strftime("%Y-%m-%d")
    close_df = D.features(instruments, ["$close"], start_time=start_time, end_time=end_time)
    if close_df is None or len(close_df) == 0:
        return trade_signal

    if isinstance(close_df, pd.Series):
        close_df = close_df.to_frame("close")
    else:
        close_df = close_df.copy()
    if isinstance(close_df.index, pd.MultiIndex):
        close_df = close_df.reset_index()
    if "datetime" not in close_df.columns or "instrument" not in close_df.columns:
        return trade_signal
    close_col = "close" if "close" in close_df.columns else close_df.columns[-1]
    close_df["datetime"] = pd.to_datetime(close_df["datetime"], errors="coerce")
    close_df["instrument"] = close_df["instrument"].astype(str)
    close_df[close_col] = pd.to_numeric(close_df[close_col], errors="coerce")
    close_df = close_df[["datetime", "instrument", close_col]].dropna()
    close_df = close_df.rename(columns={close_col: "close"})

    merged = df.merge(close_df, on=["datetime", "instrument"], how="left")
    merged = merged[pd.to_numeric(merged["close"], errors="coerce").fillna(np.inf) <= float(price_cap)]
    if merged.empty:
        return trade_signal.iloc[0:0]

    merged = merged.drop(columns=["close"]).drop_duplicates(subset=["datetime", "instrument"], keep="last")
    merged = merged.sort_values(["datetime", "instrument"])
    keep_cols = [c for c in value_cols if c in merged.columns]
    merged = merged.set_index(["datetime", "instrument"])[keep_cols]
    merged.index = merged.index.set_names(["datetime", "instrument"])
    return merged


def _write_full_backtest_report(
    output_root: Path,
    analysis_root: Path,
    fold_rows: list[dict[str, object]],
    fold_outputs: list[Path],
    template_cfg: dict,
    uri_folder: str,
    hold_num: int,
) -> None:
    from qlib.contrib.evaluate import backtest_daily
    from qlib.config import C
    import qlib
    import importlib

    raw_signal_df = _build_full_signal(fold_outputs)
    full_dir = output_root / "full_backtest"
    full_dir.mkdir(parents=True, exist_ok=True)
    analysis_root.mkdir(parents=True, exist_ok=True)
    report_txt = analysis_root / "report_of_backtest.txt"

    if raw_signal_df.empty:
        report_txt.write_text("No signal data available for full-cycle backtest.", encoding="utf-8")
        return

    # Reuse the template qlib configuration to guarantee identical data access.
    qlib_init = template_cfg.get("qlib_init", {})
    exp_manager = C["exp_manager"]
    exp_manager["kwargs"]["uri"] = "file:" + str(Path(os.getcwd()).resolve() / uri_folder)
    qlib.init(**qlib_init, exp_manager=exp_manager)

    backtest_cfg = template_cfg.get("port_analysis_config", {}).get("backtest", {})
    benchmark = backtest_cfg.get("benchmark", "SH000300")
    exchange_kwargs = backtest_cfg.get(
        "exchange_kwargs",
        {
            "freq": "day",
            "limit_threshold": 0.095,
            "deal_price": "close",
            "open_cost": 0.0005,
            "close_cost": 0.0015,
            "min_cost": 5,
        },
    )
    account = float(os.environ.get("CASH_TOTAL", 100000))

    raw_signal_series = raw_signal_df["score"].sort_index()
    signal_start = raw_signal_series.index.get_level_values("datetime").min()
    signal_end = raw_signal_series.index.get_level_values("datetime").max()

    from qlib.data import D

    cal = pd.DatetimeIndex(pd.to_datetime(D.calendar(start_time=signal_start, end_time=signal_end + pd.Timedelta(days=30), freq="day")))
    if len(cal) == 0:
        raise RuntimeError("Unable to load trading calendar for full-cycle backtest")
    end_pos = int(cal.searchsorted(signal_end, side="right")) - 1
    backtest_end = pd.Timestamp(cal[min(end_pos + 5, len(cal) - 1)])

    price_cap = _get_price_cap()
    full_backtest_strategy = str(os.environ.get("FULL_BACKTEST_STRATEGY", "stage36_risk_parity") or "stage36_risk_parity").strip().lower()

    if full_backtest_strategy == "buffered_equal_weight_topk":
        shifted_signal = _build_buffered_equal_weight_signal(
            raw_signal_df,
            cal=cal,
            hold_num=hold_num,
            price_cap=price_cap,
            dropout_buffer_pct=float(os.environ.get("FULL_BACKTEST_BUFFER_PCT", "0.5") or 0.5),
        )
        signal_source = "raw_stage2_score_buffered_topk"
        portfolio_construction = (
            f"Top{hold_num} equal-weight target position; sell only after falling out of top {int(float(os.environ.get('FULL_BACKTEST_BUFFER_PCT', '0.5') or 0.5) * 100)}% of cross-sectional score rank"
        )
        risk_degree = 1.0
    else:
        replay_signal_df = _build_stage36_full_signal(fold_outputs, output_root, hold_num)
        portfolio_signal_df = replay_signal_df if not replay_signal_df.empty else _build_risk_parity_signal_from_raw_signal(raw_signal_df, hold_num=hold_num)
        signal_source = "stage36_replay_risk_parity" if not replay_signal_df.empty else "raw_stage2_risk_parity_fallback"
        shifted_signal = _shift_signal_to_next_trade_dates(portfolio_signal_df, cal)
        shifted_signal = _apply_price_cap_to_trade_signal(shifted_signal, price_cap=price_cap)
        if not shifted_signal.empty and "weight" not in shifted_signal.columns:
            shifted_signal = shifted_signal.copy()
            shifted_signal["weight"] = shifted_signal["score"]
        portfolio_construction = "Risk Parity weighted target position"
        risk_degree = 0.95

    if shifted_signal.empty:
        report_txt.write_text(
            "Signal data exists, but no eligible trade dates remain after applying the backtest selection rules.",
            encoding="utf-8",
        )
        return

    weekly_signal = shifted_signal.reset_index().copy()
    raw_signal_df.reset_index().to_csv(full_dir / "signal_raw.csv", index=False, encoding="utf-8-sig")
    weekly_signal.to_csv(full_dir / "signal.csv", index=False, encoding="utf-8-sig")
    shifted_signal.reset_index().to_csv(full_dir / "trade_signal.csv", index=False, encoding="utf-8-sig")
    signal_diag = _signal_coverage_diagnostics(shifted_signal, cal)
    trade_start = shifted_signal.index.get_level_values("datetime").min()
    trade_end = shifted_signal.index.get_level_values("datetime").max()

    strategy = PrecomputedWeightStrategy.create(signal=shifted_signal, risk_degree=risk_degree)

    report_normal, _positions_normal = backtest_daily(
        start_time=trade_start,
        end_time=backtest_end,
        strategy=strategy,
        account=account,
        benchmark=benchmark,
        exchange_kwargs=exchange_kwargs,
    )

    report_csv = full_dir / "report_normal.csv"
    report_normal.to_csv(report_csv, encoding="utf-8-sig")

    metrics = _backtest_metrics_from_report(report_normal)
    daily = report_normal.copy()
    daily.index = pd.to_datetime(daily.index)
    for col in ["return", "cost", "bench", "turnover"]:
        if col not in daily.columns:
            daily[col] = 0.0
        daily[col] = pd.to_numeric(daily[col], errors="coerce").fillna(0.0)

    daily["strategy_return"] = daily["return"] - daily["cost"]
    daily["excess_return"] = daily["strategy_return"] - daily["bench"]
    daily["equity_curve"] = (1 + daily["strategy_return"]).cumprod()
    daily["excess_curve"] = (1 + daily["excess_return"]).cumprod()
    daily["drawdown"] = daily["equity_curve"] / daily["equity_curve"].cummax() - 1
    daily.to_csv(full_dir / "equity_curve.csv", encoding="utf-8-sig")

    # ── Qlib native report figures ────────────────────────────────────────
    native_report_figs: list = []
    native_ic_figs: list = []
    native_cumret_figs: list = []
    native_rank_figs: list = []
    try:
        analysis_position = importlib.import_module("qlib.contrib.report.analysis_position")
        native_report_figs = list(analysis_position.report_graph(report_normal, show_notebook=False))

        # Build labels and positions for native IC / cumulative return / rank analysis.
        from qlib.data import D

        label_start = pd.to_datetime(signal_start).strftime("%Y-%m-%d")
        label_end = pd.to_datetime(backtest_end).strftime("%Y-%m-%d")
        trade_instruments = sorted(shifted_signal.index.get_level_values("instrument").astype(str).unique().tolist())
        label_data = D.features(
            trade_instruments,
            ["Ref($close, -1)/$close - 1"],
            start_time=label_start,
            end_time=label_end,
        )
        if label_data is not None and not label_data.empty:
            if isinstance(label_data, pd.Series):
                label_data = label_data.to_frame("label")
            else:
                label_data = label_data.copy()
                if label_data.shape[1] != 1:
                    label_data = label_data.iloc[:, :1]
                label_data.columns = ["label"]
            label_data = label_data.dropna()

            pred_label = shifted_signal.join(label_data, how="inner")
            if not pred_label.empty:
                native_ic_figs = list(analysis_position.score_ic_graph(pred_label, show_notebook=False))
                native_cumret_figs = list(
                    analysis_position.cumulative_return_graph(
                        _positions_normal,
                        report_normal,
                        label_data,
                        show_notebook=False,
                        start_date=pd.to_datetime(trade_start).strftime("%Y-%m-%d"),
                        end_date=pd.to_datetime(trade_end).strftime("%Y-%m-%d"),
                    )
                )
                native_rank_figs = list(
                    analysis_position.rank_label_graph(
                        _positions_normal,
                        label_data,
                        start_date=pd.to_datetime(trade_start).strftime("%Y-%m-%d"),
                        end_date=pd.to_datetime(trade_end).strftime("%Y-%m-%d"),
                        show_notebook=False,
                    )
                )
    except Exception as exc:
        print(f"⚠ Qlib 原生图表生成失败: {exc}")

    fold_df = pd.DataFrame(fold_rows) if fold_rows else pd.DataFrame()
    ic_mean = float(pd.to_numeric(fold_df.get("IC_mean"), errors="coerce").mean()) if "IC_mean" in fold_df else float("nan")
    ic_std = float(pd.to_numeric(fold_df.get("IC_mean"), errors="coerce").std()) if "IC_mean" in fold_df else float("nan")
    icir = ic_mean / ic_std if pd.notna(ic_std) and ic_std not in (0, 0.0) else float("nan")
    ic_count = int(pd.to_numeric(fold_df.get("IC_mean"), errors="coerce").dropna().shape[0]) if "IC_mean" in fold_df else 0
    ic_t_stat = (
        float(ic_mean / (ic_std / np.sqrt(ic_count)))
        if ic_count > 1 and pd.notna(ic_std) and ic_std > 0
        else float("nan")
    )

    summary_lines = [
        f"Full-cycle Top{hold_num} walk-forward backtest",
        "====================================",
        f"Signals: {signal_start.date()} -> {signal_end.date()}",
        f"Trade signals: {trade_start.date()} -> {trade_end.date()}",
        f"Backtest end: {backtest_end.date()}",
        f"Account: {account:.2f}",
        f"Benchmark: {benchmark}",
        f"Signal source: {signal_source}",
        f"Portfolio construction: {portfolio_construction}",
        f"Trade signal dates: {int(signal_diag['trade_signal_dates'])}",
        f"Calendar days in span: {int(signal_diag['calendar_days'])}",
        f"Signal coverage ratio: {signal_diag['signal_coverage_ratio']:.6f}",
        f"Median gap between signal dates: {signal_diag['median_gap_days']:.2f} trading days",
        f"Max gap between signal dates: {signal_diag['max_gap_days']:.2f} trading days",
        f"Mean turnover: {metrics['turnover_mean']:.6f}",
        f"Total turnover: {metrics['turnover_sum']:.6f}",
        f"Annualized return: {metrics['annualized_return']:.6f}",
        f"Max drawdown: {metrics['max_drawdown']:.6f}",
        f"Sharpe ratio: {metrics['sharpe_ratio']:.6f}",
        f"Information ratio: {metrics['information_ratio']:.6f}",
        f"Monthly win rate: {metrics['monthly_win_rate']:.6f}",
        f"IC mean: {ic_mean:.6f}",
        f"ICIR: {icir:.6f}",
        f"IC t-stat: {ic_t_stat:.6f}",
        "",
    ]

    # Lightweight expert-style commentaries for fast inspection.
    if pd.notna(signal_diag["signal_coverage_ratio"]) and signal_diag["signal_coverage_ratio"] < 0.2:
        commentary = (
            "Signal coverage is sparse relative to the trading calendar; the full-cycle backtest should be interpreted "
            "as a sparse-signal replay rather than a fully continuous daily portfolio."
        )
    elif pd.notna(metrics["annualized_return"]):
        if metrics["annualized_return"] > 0 and (pd.isna(metrics["max_drawdown"]) or metrics["max_drawdown"] > -0.3):
            commentary = "Strategy quality is acceptable: positive return with controllable drawdown."
        elif metrics["annualized_return"] > 0:
            commentary = "Strategy is profitable but drawdown remains material; risk control needs further tuning."
        else:
            commentary = "Strategy underperforms on a net basis; factor decay or transaction cost sensitivity likely dominates."
    else:
        commentary = "Insufficient data for a stable judgment."

    summary_lines.append(f"Expert commentary: {commentary}")
    report_txt.write_text("\n".join(summary_lines), encoding="utf-8")

    def _fig_block(fig) -> str:
        try:
            return fig.to_html(full_html=False, include_plotlyjs=False)
        except Exception:
            return ""

    sections_html = []
    all_figs = [
        ("组合回测报告", native_report_figs, "qlib.contrib.report.analysis_position.report_graph"),
        ("Score IC 分析", native_ic_figs, "qlib.contrib.report.analysis_position.score_ic_graph"),
        ("买卖持有累计收益", native_cumret_figs, "qlib.contrib.report.analysis_position.cumulative_return_graph"),
        ("持仓标签分位", native_rank_figs, "qlib.contrib.report.analysis_position.rank_label_graph"),
    ]
    for title, figs, desc in all_figs:
        parts = ["<div class=\"card\">", f"<h2>{title}</h2>", f"<div class=\"muted\">{desc}</div>"]
        if figs:
            for fig in figs:
                parts.append('<div style="margin-top:16px;">')
                parts.append(_fig_block(fig))
                parts.append("</div>")
        else:
            parts.append("<div class=\"muted\">无可用图表。</div>")
        parts.append("</div>")
        sections_html.append("\n".join(parts))

    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <title>Full-cycle Backtest Overview</title>
    <script src="https://cdn.plot.ly/plotly-3.4.0.min.js"></script>
  <style>
    body {{ font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; margin: 24px; color: #1f2937; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }}
    th {{ background: #f9fafb; width: 260px; }}
    .card {{ border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; margin-bottom: 20px; }}
    .muted {{ color: #6b7280; }}
  </style>
</head>
<body>
    <h1>Full-cycle Top{hold_num} Walk-forward Backtest</h1>
        <div class="muted">Aggregated from fold-level OOS predictions. This page now uses Qlib native report graphs.</div>
    <div class="card">
        <h2>Metrics</h2>
        <table>
            {''.join(f'<tr><th>{k}</th><td>{v:.6f}</td></tr>' for k, v in metrics.items())}
        </table>
    </div>
        <div class="card">
                <h2>Signal coverage diagnostics</h2>
                <table>
                        <tr><th>trade_signal_dates</th><td>{int(signal_diag['trade_signal_dates'])}</td></tr>
                        <tr><th>calendar_days</th><td>{int(signal_diag['calendar_days'])}</td></tr>
                        <tr><th>signal_coverage_ratio</th><td>{signal_diag['signal_coverage_ratio']:.6f}</td></tr>
                        <tr><th>median_gap_days</th><td>{signal_diag['median_gap_days']:.2f}</td></tr>
                        <tr><th>max_gap_days</th><td>{signal_diag['max_gap_days']:.2f}</td></tr>
                </table>
        </div>
    {''.join(sections_html)}
</body>
</html>
"""
    full_overview = full_dir / "overview.html"
    full_overview.write_text(html, encoding="utf-8")
    shutil.copy2(full_overview, output_root / "full_backtest_overview.html")

    print(f"✓ Full-cycle backtest report: {report_txt}")
    print(f"✓ Full-cycle overview: {full_overview}")
    print(f"✓ Full-cycle daily report: {report_csv}")
    print(f"✓ Full-cycle equity curve: {full_dir / 'equity_curve.csv'}")
    print(f"✓ Full-cycle signal: {full_dir / 'signal.csv'}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True, help="Base workflow YAML template")
    ap.add_argument("--output-root", required=True, help="Root output dir, usually .../model_predict")
    ap.add_argument("--analysis-root", required=True, help="Experiment root dir, used for backtest report output")
    ap.add_argument("--experiment-name", required=True)
    ap.add_argument("--latest-pred-date", default=None)
    ap.add_argument("--uri-folder", default="mlruns")
    ap.add_argument("--half-life", type=int, default=252)
    ap.add_argument("--floor", type=float, default=0.2)
    ap.add_argument("--step-years", type=int, default=1,
                    help="Walk-forward stride in years (annual mode). Overrides --step-weeks when > 0.")
    ap.add_argument("--step-weeks", type=int, default=0,
                    help="Walk-forward stride in weeks (weekly mode, used only when --step-years=0)")
    ap.add_argument("--test-years", type=int, default=3,
                    help="Test window width in years (annual mode only)")
    ap.add_argument("--test-weeks", type=int, default=52,
                    help="Test window width in weeks (weekly mode only; annual mode uses --test-years)")
    ap.add_argument("--train-years", type=int, default=7)  # 7y train window
    ap.add_argument("--valid-years", type=int, default=2)
    ap.add_argument("--history-years", type=int, default=10,
                    help="Annual mode only: roll backward from the latest anchor for at most this many years")
    ap.add_argument("--train-base-start", default="2008-01-01")
    ap.add_argument("--walk-forward-start", default="2008-01-01")
    ap.add_argument("--walk-forward-end", required=True)
    ap.add_argument("--hold-num", type=int, default=int(os.environ.get("HOLD_NUM", "5")))
    ap.add_argument("--segment-years", type=int, default=1, help="Group folds into year chunks for staged execution")
    ap.add_argument("--model-mode", choices=["default", "robust"], default="robust")
    args = ap.parse_args()

    template_path = Path(args.template)
    if not template_path.exists():
        template_str = str(template_path)
        workspace_root = str(ROOT)
        if template_str.startswith(workspace_root):
            template_path = ROOT / template_path.relative_to(workspace_root)
        elif template_str.startswith("/Users/apple/gitee/qlib"):
            rel = Path(template_str[len("/Users/apple/gitee/qlib"):].lstrip("/"))
            template_path = ROOT / rel
        elif template_str.startswith("/work"):
            rel = Path(template_str[len("/work"):].lstrip("/"))
            template_path = ROOT / rel

    if args.step_years <= 0 and args.step_weeks <= 0:
        raise ValueError("Either --step-years or --step-weeks must be positive")
    if args.train_years <= 0 or args.valid_years <= 0:
        raise ValueError("train-years and valid-years must be positive")
    if args.hold_num <= 0:
        raise ValueError("hold-num must be positive")
    if args.half_life <= 0:
        raise ValueError("half-life must be positive")
    if not (0 < args.floor <= 1):
        raise ValueError("floor must be in (0, 1]")

    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    wf_root = output_root / "walk_forward"
    wf_root.mkdir(parents=True, exist_ok=True)
    mlruns_root = ROOT / args.uri_folder

    env = os.environ.copy()
    fold_rows: list[dict[str, object]] = []
    fold_outputs: list[Path] = []
    latest_fold_output: Path | None = None
    latest_fold_tag: str | None = None
    previous_checkpoints: dict[str, Path] = {}

    walk_forward_end = args.walk_forward_end or args.latest_pred_date
    if not walk_forward_end:
        raise ValueError("walk-forward-end or latest-pred-date must be provided")

    template_cfg, calendar = _load_trade_calendar(
        template_path=template_path,
        uri_folder=args.uri_folder,
        start_date=args.train_base_start,
        end_date=walk_forward_end,
    )
    calendar_end = pd.Timestamp(calendar.max())
    requested_end = pd.Timestamp(walk_forward_end)
    effective_end = min(requested_end, calendar_end)
    effective_end_str = _fmt(effective_end)
    if effective_end < requested_end:
        print(
            f"⚠ Requested walk-forward end {requested_end.date()} exceeds local qlib data. "
            f"Clipped to latest trade date {calendar_end.date()}."
        )

    folds = _build_fold_dates(
        calendar=calendar,
        start_date=args.walk_forward_start,
        end_date=effective_end_str,
        step_years=args.step_years,
        step_weeks=args.step_weeks,
        test_years=args.test_years,
        test_weeks=args.test_weeks,
        train_years=args.train_years,
        valid_years=args.valid_years,
        train_base_start=args.train_base_start,
        history_years=args.history_years,
    )

    _mode = f"{args.step_years}y" if args.step_years > 0 else f"{args.step_weeks}w"
    _test_win = f"{args.test_years} year(s)" if args.step_years > 0 else f"{args.step_weeks} week(s)"
    print("═══════════════════════════════════════════════")
    print("Walk-forward stage2 plan")
    print(f"  window  : train={args.train_years}y  dev={args.valid_years}y  test={_test_win}")
    print(f"  stride  : {_mode}  ({'annual' if args.step_years > 0 else 'weekly'} mode)")
    if args.step_years > 0:
        print(f"  history : {args.history_years} year(s)")
    print(f"  range   : {args.walk_forward_start} -> {effective_end_str}")
    print(f"  data max: {calendar_end.date()}")
    print(f"  segment : {args.segment_years} year(s)")
    for i, fold in enumerate(folds, start=1):
        print(
            f"  [{i:04d}/{len(folds):04d}] signal={fold['signal_date']} pred={fold['pred_date']} test={fold['test_start']} ~ {fold['test_end']} oos={fold['test_start']} ~ {fold['oos_end']} "
            f"train={fold['train_start']} ~ {fold['train_end']} valid={fold['valid_start']} ~ {fold['valid_end']}"
        )
    print("═══════════════════════════════════════════════")

    if not folds:
        raise RuntimeError(
            f"No valid walk-forward folds generated for {args.walk_forward_start} -> {effective_end_str}. "
            "Check train-years/valid-years/test-years against the local qlib calendar coverage."
        )

    segment_groups = _group_folds_by_year(folds, args.segment_years)
    fold_index = 0
    for segment_key, segment_folds in segment_groups:
        segment_dir = wf_root / "segments" / segment_key
        segment_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n════════════ Segment {segment_key} ({len(segment_folds)} folds) ════════════")

        for fold in segment_folds:
            fold_index += 1
            fold_tag = fold["signal_date"]
            fold_dir = wf_root / fold_tag
            fold_dir.mkdir(parents=True, exist_ok=True)
            fold_run_dir = fold_dir / "ensemble_run"
            fold_output = fold_dir / "model_predict"

            print(
                f"\n[{fold_index}/{len(folds)}] Fold {fold_tag}: {fold['train_start']} ~ {fold['train_end']} | "
                f"{fold['valid_start']} ~ {fold['valid_end']} | test={fold['test_start']} ~ {fold['test_end']} | oos={fold['test_start']} ~ {fold['oos_end']}"
            )

            # ① Skip fold if already completed (resume support); regenerate exports if the cached run exists.
            if (not _fold_output_ready(fold_output)) and fold_run_dir.exists():
                print(f"  ↻ Fold {fold_tag}: cached mlflow run found — regenerating missing exports")
                _export_fold_outputs(fold_run_dir, fold_output, fold["pred_date"], env)

            if _fold_output_matches_window(fold_output, fold["pred_date"], fold["oos_end"]):
                print(f"  ↩ Fold {fold_tag}: scores.csv exists — SKIPPED (resuming)")
                metrics_csv = fold_output / "metrics.csv"
                metrics = pd.read_csv(metrics_csv).iloc[0].to_dict() if metrics_csv.exists() else {}
                for spec in MODEL_SPECS:
                    model_name = str(spec["name"])
                    ckpt = fold_dir / "model_runs" / model_name / "mlflow_run" / "artifacts" / "params.pkl"
                    if ckpt.exists():
                        previous_checkpoints[model_name] = ckpt
                metrics.update(
                    {
                        "fold": fold_index,
                        "fold_tag": fold_tag,
                        "segment": segment_key,
                        "signal_date": fold["signal_date"],
                        "train_start": fold["train_start"],
                        "train_end": fold["train_end"],
                        "valid_start": fold["valid_start"],
                        "valid_end": fold["valid_end"],
                        "test_start": fold["test_start"],
                        "test_end": fold["test_end"],
                        "pred_date": fold["pred_date"],
                        "oos_end": fold["oos_end"],
                        "skipped": True,
                    }
                )
                fold_rows.append(metrics)
                fold_outputs.append(fold_output)
                latest_fold_output = fold_output
                latest_fold_tag = fold_tag
                continue
            elif _fold_output_ready(fold_output):
                print(f"  ↻ Fold {fold_tag}: cached outputs do not match target OOS horizon — retraining")
            metrics = _build_ensemble_fold_output(
                fold=fold,
                fold_dir=fold_dir,
                fold_output=fold_output,
                mlruns_root=mlruns_root,
                template_cfg=template_cfg,
                base_env=env,
                args=args,
                previous_checkpoints=previous_checkpoints,
            )
            for spec in MODEL_SPECS:
                model_name = str(spec["name"])
                ckpt = fold_dir / "model_runs" / model_name / "mlflow_run" / "artifacts" / "params.pkl"
                if ckpt.exists():
                    previous_checkpoints[model_name] = ckpt
            metrics.update(
                {
                    "fold": fold_index,
                    "fold_tag": fold_tag,
                    "segment": segment_key,
                    "signal_date": fold["signal_date"],
                    "train_start": fold["train_start"],
                    "train_end": fold["train_end"],
                    "valid_start": fold["valid_start"],
                    "valid_end": fold["valid_end"],
                    "test_start": fold["test_start"],
                    "test_end": fold["test_end"],
                    "pred_date": fold["pred_date"],
                    "oos_end": fold["oos_end"],
                }
            )
            fold_rows.append(metrics)
            fold_outputs.append(fold_output)
            latest_fold_output = fold_output
            latest_fold_tag = fold_tag

        # per-segment summary for resumability / inspection
        segment_rows = [row for row in fold_rows if row.get("segment") == segment_key]
        if segment_rows:
            segment_df = pd.DataFrame(segment_rows)
            segment_df.to_csv(segment_dir / "segment_folds.csv", index=False, encoding="utf-8-sig")
            (segment_dir / "segment_summary.txt").write_text(
                f"Segment {segment_key}\nFolds: {len(segment_rows)}\nLatest fold: {segment_rows[-1].get('fold_tag')}\n",
                encoding="utf-8",
            )

    if latest_fold_output is None or latest_fold_tag is None:
        raise RuntimeError("No walk-forward folds were completed")

    # Preserve the latest fold outputs at the root for stage3/4/5/6.
    _copy_fold_outputs(latest_fold_output, output_root)

    # Save fold-level and aggregate reports.
    _generate_summary(fold_rows, output_root)

    # Full-cycle consolidated backtest from all weekly fold signals.
    _write_full_backtest_report(output_root, Path(args.analysis_root), fold_rows, fold_outputs, template_cfg, args.uri_folder, args.hold_num)

    print("\n═══════════════════════════════════════════════")
    print(f"Latest fold copied to root output: {latest_fold_tag}")
    print(f"Walk-forward fold summary: {output_root / 'walk_forward_folds.csv'}")
    print(f"Walk-forward aggregate summary: {output_root / 'walk_forward_summary.csv'}")
    print(f"Full-cycle backtest report: {Path(args.analysis_root) / 'report_of_backtest.txt'}")
    print("═══════════════════════════════════════════════")


if __name__ == "__main__":
    main()